### ISSUE TITLE
Exp simulation needs to perform pick and place

### ISSUE THREAD

**Issue by LiamMZ** [HIRO-group/torque_constrained_motion_planning#1]
Currently, the robot only plans a trajectory to the payload and doesn't move the object to goal location. Additionally, the robot plans this trajectory assuming it needs to be torque limited by the payload. the trajectories should be planned as follows:

1. The robot should move into an approach position assuming payload is zero
2. the robot should move to a grasp position taking the payload into account
3. the robot should move to the place position taking the payload into account

**Comment by a-nooj** [comment]
Payload should only be taken into account after the robot has securely
grasped the object.
